name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
